openapi: 3.0.0
info:
  title: Chess Tournament API
  version: 1

servers:
  - url: http://localhost:4444/api
    description: local server
  - url: https://chess-tournament-api.devtest.ge/api
    description: production server

paths:
  /grandmasters:
    get:
      tags:
        - Services
      responses:
        '200':
          description: Get all the grandmasters
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      required: true
                    name:
                      type: string
                      required: true
                    image:
                      type: string
                      required: true
                  example:
                      id: 1
                      name: Nona Gaphrindashvili
                      image: /images/nona.jpg
